// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BaseDeDatos.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BaseDeDatos.Models
{
    public partial class cineContext
    {
        private IcineContextProcedures _procedures;

        public virtual IcineContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new cineContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IcineContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class cineContextProcedures : IcineContextProcedures
    {
        private readonly cineContext _context;

        public cineContextProcedures(cineContext context)
        {
            _context = context;
        }

        public virtual async Task<List<horarios_popularesResult>> horarios_popularesAsync(string Tipo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Tipo",
                    Size = 30,
                    Value = Tipo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<horarios_popularesResult>("EXEC @returnValue = [dbo].[horarios_populares] @Tipo = @Tipo", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
