// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BaseDeDatos.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BaseDeDatos.Models
{
    public partial interface IcineContextProcedures
    {
        Task<List<horarios_popularesResult>> horarios_popularesAsync(string Tipo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
