// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseDeDatos.Models;

public partial class Transaccione
{
    public int CodTransaccion { get; set; }

    public int? CantidadTicket { get; set; }

    public DateTime? FechaCompra { get; set; }

    public int? CodPago { get; set; }

    public int? IdEstado { get; set; }

    public int? IdCliente { get; set; }

    public virtual MetodosPago CodPagoNavigation { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Estado IdEstadoNavigation { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}